Terraform, github workflows, README.md
Terraform cleanup
github workflows updates
README update

diff --git a/.github/workflows/build-snarkos.yml b/.github/workflows/build-snarkos.yml
--- a/.github/workflows/build-snarkos.yml
+++ b/.github/workflows/build-snarkos.yml
@@ -32,12 +32,12 @@ jobs:
         uses: google-github-actions/setup-gcloud@v2
         with:
           project_id: ${{ env.GCP_PROJECT_ID }}
-          service_account_key: ${{ secrets.IMAGE_BUILDER_KEY }}
+          service_account_key: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}
 
       - name: Authenticate to Google Cloud
         uses: google-github-actions/auth@v2
         with:
-          credentials_json: ${{ secrets.IMAGE_BUILDER_KEY }}
+          credentials_json: ${{ secrets.GCP_SA_IMG_BUILDER_KEY }}
 
       - name: Configure Docker for Artifact Registry
         run: |
@@ -46,23 +46,35 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v3
 
-      - name: Map NETWORK_NAME to NETWORK number
+      - name: Map NETWORK_NAME to NETWORK number and directory
         id: network-map
         run: |
           case "${{ github.event.inputs.network_name }}" in
-            mainnet) echo "NETWORK=0" >> $GITHUB_ENV ;;
-            testnet) echo "NETWORK=1" >> $GITHUB_ENV ;;
-            canary)  echo "NETWORK=2" >> $GITHUB_ENV ;;
-            *) echo "ERROR: Unknown network '${{ github.event.inputs.network_name }}'." && exit 1 ;;
+            mainnet)
+              echo "NETWORK=0" >> $GITHUB_ENV
+              echo "NETWORK_DIR=mainnet" >> $GITHUB_ENV
+              ;;
+            testnet)
+              echo "NETWORK=1" >> $GITHUB_ENV
+              echo "NETWORK_DIR=testnet" >> $GITHUB_ENV
+              ;;
+            canary)
+              echo "NETWORK=2" >> $GITHUB_ENV
+              echo "NETWORK_DIR=canary" >> $GITHUB_ENV
+              ;;
+            *)
+              echo "ERROR: Unknown network '${{ github.event.inputs.network_name }}'." && exit 1
+              ;;
           esac
+
 
       - name: Build and Push Multi-Arch Image
         uses: docker/build-push-action@v5
         with:
           context: .
           push: true
-          platforms: linux/amd64,linux/arm64
-          tags: us-east1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/snarkos:${{ github.event.inputs.image_tag }}
+          platforms: linux/amd64
+          tags: us-east1-docker.pkg.dev/${{ env.GCP_PROJECT_ID }}/${{ env.GCP_ARTIFACT_REPO }}/${{ env.NETWORK_DIR }}/snarkos:${{ github.event.inputs.image_tag }}
           build-args: |
             GIT_REF=${{ github.event.inputs.git_ref }}
             NETWORK=${{ env.NETWORK }}
